version: '3.8'

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile.dev.yaml
    command: ./app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./database:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
